/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  PostAuthForgotPasswordBody,
  PostAuthLogin200,
  PostAuthLoginBody,
  PostAuthSignup201,
  PostAuthSignupBody,
  PutAuthUpdatePasswordBody,
  PutAuthUpdatePasswordParams,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getAuth = () => {
  /**
   * Signs Up New User to the Platform as a Therapist
   * @summary SignUp Feature
   */
  const postAuthSignup = (postAuthSignupBody: PostAuthSignupBody) => {
    return customAxios<PostAuthSignup201>({
      url: `/auth/signup`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthSignupBody,
    });
  };
  /**
   * Log into the Platform
   * @summary Login Feature
   */
  const postAuthLogin = (postAuthLoginBody: PostAuthLoginBody) => {
    return customAxios<PostAuthLogin200>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthLoginBody,
    });
  };
  /**
   * Forgot Password? Reset it here!
   * @summary Forgot Password Feature
   */
  const postAuthForgotPassword = (
    postAuthForgotPasswordBody: PostAuthForgotPasswordBody,
  ) => {
    return customAxios<void>({
      url: `/auth/forgot-password`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthForgotPasswordBody,
    });
  };
  /**
   * Update your password for your account using a reset token
   * @summary Updating Password Feature
   */
  const putAuthUpdatePassword = (
    putAuthUpdatePasswordBody: PutAuthUpdatePasswordBody,
    params?: PutAuthUpdatePasswordParams,
  ) => {
    return customAxios<void>({
      url: `/auth/update-password`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: putAuthUpdatePasswordBody,
      params,
    });
  };
  /**
   * Delete your Account here! Requires authentication via JWT token in cookies. You can only delete your own account.
   * @summary Delete Account Feature
   */
  const deleteAuthDeleteAccountId = (id: string) => {
    return customAxios<void>({
      url: `/auth/delete-account/${id}`,
      method: "DELETE",
    });
  };
  return {
    postAuthSignup,
    postAuthLogin,
    postAuthForgotPassword,
    putAuthUpdatePassword,
    deleteAuthDeleteAccountId,
  };
};
export type PostAuthSignupResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postAuthSignup"]>>
>;
export type PostAuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postAuthLogin"]>>
>;
export type PostAuthForgotPasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postAuthForgotPassword"]>>
>;
export type PutAuthUpdatePasswordResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["putAuthUpdatePassword"]>>
>;
export type DeleteAuthDeleteAccountIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["deleteAuthDeleteAccountId"]>>
>;
