/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  PostAuthLogin200,
  PostAuthLoginBody,
  PostAuthSignup201,
  PostAuthSignupBody,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getAuth = () => {
  /**
   * Signs Up New User to the Platform as a Therapist
   * @summary SignUp Feature
   */
  const postAuthSignup = (postAuthSignupBody: PostAuthSignupBody) => {
    return customAxios<PostAuthSignup201>({
      url: `/auth/signup`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthSignupBody,
    });
  };
  /**
   * Log into the Platform
   * @summary Login Feature
   */
  const postAuthLogin = (postAuthLoginBody: PostAuthLoginBody) => {
    return customAxios<PostAuthLogin200>({
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postAuthLoginBody,
    });
  };
  return { postAuthSignup, postAuthLogin };
};
export type PostAuthSignupResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postAuthSignup"]>>
>;
export type PostAuthLoginResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getAuth>["postAuthLogin"]>>
>;
