/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type { District } from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getDistricts = () => {
  /**
   * Retrieve all districts from the system
   * @summary Get all districts
   */
  const getDistricts = () => {
    return customAxios<District[]>({ url: `/districts`, method: "GET" });
  };
  /**
   * Retrieve a district by its numeric ID
   * @summary Get district by ID
   */
  const getDistrictsId = (id: number) => {
    return customAxios<District>({ url: `/districts/${id}`, method: "GET" });
  };
  return { getDistricts, getDistrictsId };
};
export type GetDistrictsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDistricts>["getDistricts"]>>
>;
export type GetDistrictsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getDistricts>["getDistrictsId"]>>
>;
