/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GameContent,
  GetGameContentsParams,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getGameContent = () => {
  /**
   * Get all Game Contents for given category and level with a certain number of words
   * @summary Get Game Contents
   */
  const getGameContents = (params?: GetGameContentsParams) => {
    return customAxios<GameContent[]>({
      url: `/game-contents`,
      method: "GET",
      params,
    });
  };
  return { getGameContents };
};
export type GetGameContentsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getGameContent>["getGameContents"]>>
>;
