/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetNewsletterByDate200,
  GetNewsletterByDateParams,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getNewsletter = () => {
  /**
   * Retrieve a newsletter for a specific date and generate a presigned URL to access it from S3
   * @summary Get newsletter by date
   */
  const getNewsletterByDate = (params: GetNewsletterByDateParams) => {
    return customAxios<GetNewsletterByDate200>({
      url: `/newsletter/by-date`,
      method: "GET",
      params,
    });
  };
  return { getNewsletterByDate };
};
export type GetNewsletterByDateResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getNewsletter>["getNewsletterByDate"]>>
>;
