/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type { GetSchoolsParams, School } from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getSchools = () => {
  /**
   * Retrieve all schools, or filter by district using the `district_id` query parameter.
   * @summary Get schools
   */
  const getSchools = (params?: GetSchoolsParams) => {
    return customAxios<School[]>({ url: `/schools`, method: "GET", params });
  };
  return { getSchools };
};
export type GetSchoolsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSchools>["getSchools"]>>
>;
