/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  ModifySessionResource,
  SessionResource,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getSessionResource = () => {
  /**
   * Create a new association between each session and a utilized resource
   * @summary Create a session-resource link
   */
  const postSessionResource = (
    modifySessionResource: ModifySessionResource,
  ) => {
    return customAxios<SessionResource>({
      url: `/session-resource`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: modifySessionResource,
    });
  };
  /**
   * Delete an existing association between a session and a resource
   * @summary Delete a session-resource link
   */
  const deleteSessionResource = (
    modifySessionResource: ModifySessionResource,
  ) => {
    return customAxios<void>({
      url: `/session-resource`,
      method: "DELETE",
      headers: { "Content-Type": "application/json" },
      data: modifySessionResource,
    });
  };
  return { postSessionResource, deleteSessionResource };
};
export type PostSessionResourceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessionResource>["postSessionResource"]>
  >
>;
export type DeleteSessionResourceResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessionResource>["deleteSessionResource"]>
  >
>;
