/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateSessionStudentInput,
  DeleteSessionStudentsBody,
  SessionStudent,
  UpdateSessionStudentInput,
} from './theSpecialStandardAPI.schemas'

import { customAxios } from './apiClient'

export function getSessionStudents() {
  /**
   * Associate each given student with each given session, creating an entry in the bridge table
   * @summary Create session-student relationship
   */
  const postSessionStudents = (
    createSessionStudentInput: CreateSessionStudentInput,
  ) => {
    return customAxios<SessionStudent[]>({
      url: `/session_students`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createSessionStudentInput,
    })
  }
  /**
   * Remove the association between a student and a session
   * @summary Delete session-student relationship
   */
  const deleteSessionStudents = (
    deleteSessionStudentsBody: DeleteSessionStudentsBody,
  ) => {
    return customAxios<void>({
      url: `/session_students`,
      method: 'DELETE',
      headers: { 'Content-Type': 'application/json' },
      data: deleteSessionStudentsBody,
    })
  }
  /**
   * Update the present status or notes for a session-student relationship
   * @summary Update session-student relationship
   */
  const patchSessionStudents = (
    updateSessionStudentInput: UpdateSessionStudentInput,
  ) => {
    return customAxios<SessionStudent>({
      url: `/session_students`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateSessionStudentInput,
    })
  }
  return { postSessionStudents, deleteSessionStudents, patchSessionStudents }
}
export type PostSessionStudentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessionStudents>['postSessionStudents']>
  >
>
export type DeleteSessionStudentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessionStudents>['deleteSessionStudents']>
  >
>
export type PatchSessionStudentsResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSessionStudents>['patchSessionStudents']>
  >
>
