/**
 * Generated by orval v7.13.1 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  CreateTherapistInput,
  DeleteTherapistsId200,
  GetTherapistsParams,
  Therapist,
  UpdateTherapistInput,
} from './theSpecialStandardAPI.schemas'

import { customAxios } from './apiClient'

export function getTherapists() {
  /**
   * Retrieve all therapists from the database
   * @summary Get all therapists
   */
  const getTherapists = (params?: GetTherapistsParams) => {
    return customAxios<Therapist[]>({
      url: `/therapists`,
      method: 'GET',
      params,
    })
  }
  /**
   * Create a new therapist for school districts
   * @summary Create a new therapist
   */
  const postTherapists = (createTherapistInput: CreateTherapistInput) => {
    return customAxios<Therapist>({
      url: `/therapists`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      data: createTherapistInput,
    })
  }
  /**
   * Retrieve a specific therapist from the database
   * @summary Get therapist by ID
   */
  const getTherapistsId = (id: string) => {
    return customAxios<Therapist>({ url: `/therapists/${id}`, method: 'GET' })
  }
  /**
   * Update a specific field within a therapist object in the database
   * @summary Update therapist
   */
  const patchTherapistsId = (
    id: string,
    updateTherapistInput: UpdateTherapistInput,
  ) => {
    return customAxios<Therapist>({
      url: `/therapists/${id}`,
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      data: updateTherapistInput,
    })
  }
  /**
   * Get the specific therapist corresponding to the given ID and delete it
   * @summary Delete therapist
   */
  const deleteTherapistsId = (id: string) => {
    return customAxios<DeleteTherapistsId200>({
      url: `/therapists/${id}`,
      method: 'DELETE',
    })
  }
  return {
    getTherapists,
    postTherapists,
    getTherapistsId,
    patchTherapistsId,
    deleteTherapistsId,
  }
}
export type GetTherapistsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTherapists>['getTherapists']>>
>
export type PostTherapistsResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTherapists>['postTherapists']>>
>
export type GetTherapistsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTherapists>['getTherapistsId']>>
>
export type PatchTherapistsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTherapists>['patchTherapistsId']>>
>
export type DeleteTherapistsIdResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getTherapists>['deleteTherapistsId']>>
>
