/**
 * Generated by orval v7.16.0 🍺
 * Do not edit manually.
 * The Special Standard API
 * OpenAPI spec version: 0.1.0
 */
import type {
  PostVerificationResend200,
  PostVerificationResendBody,
  PostVerificationSendCode200,
  PostVerificationSendCodeBody,
  PostVerificationVerify200,
  PostVerificationVerifyBody,
} from "./theSpecialStandardAPI.schemas";

import { customAxios } from "./apiClient";

export const getVerification = () => {
  /**
   * Initiates MFA setup or verification by sending a code to the user. For TOTP-based MFA (Google Authenticator), returns a QR code and secret.
   * @summary Send Verification Code
   */
  const postVerificationSendCode = (
    postVerificationSendCodeBody: PostVerificationSendCodeBody,
  ) => {
    return customAxios<PostVerificationSendCode200>({
      url: `/verification/send-code`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postVerificationSendCodeBody,
    });
  };
  /**
   * Verifies a code provided by the user (from Google Authenticator or other method)
   * @summary Verify Code
   */
  const postVerificationVerify = (
    postVerificationVerifyBody: PostVerificationVerifyBody,
  ) => {
    return customAxios<PostVerificationVerify200>({
      url: `/verification/verify`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postVerificationVerifyBody,
    });
  };
  /**
   * Resends a verification code to the user (useful if the original code was lost or expired)
   * @summary Resend Verification Code
   */
  const postVerificationResend = (
    postVerificationResendBody: PostVerificationResendBody,
  ) => {
    return customAxios<PostVerificationResend200>({
      url: `/verification/resend`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: postVerificationResendBody,
    });
  };
  return {
    postVerificationSendCode,
    postVerificationVerify,
    postVerificationResend,
  };
};
export type PostVerificationSendCodeResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getVerification>["postVerificationSendCode"]>
  >
>;
export type PostVerificationVerifyResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getVerification>["postVerificationVerify"]>
  >
>;
export type PostVerificationResendResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getVerification>["postVerificationResend"]>
  >
>;
