import * as React from 'react'
import { cn } from '@/lib/utils'

// Avatar URLs from public folder
const AVATAR_SVGS = [
  '/blueStar.svg',
  '/greenStar.svg',
  '/orangeStar.svg',
  '/yellowStar.svg',
  '/redStar.svg',
  '/pinkStar.svg',
  '/purpleStar.svg',
  '/tealStar.svg',
  '/cyanStar.svg',
  '/violetStar.svg',
  '/brownStar.svg',
]

// Simple hash function to deterministically map names to avatars
function hashName(name: string): number {
  let hash = 0
  for (let i = 0; i < name.length; i++) {
    const char = name.charCodeAt(i)
    hash = ((hash << 5) - hash) + char
    hash = hash & hash // Convert to 32bit integer
  }
  return Math.abs(hash) % AVATAR_SVGS.length
}

// Avatar container component with auto-generation support
const Avatar = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement> & {
    name?: string
  }
>(({ className, name, children, ...props }, ref) => {
  const shouldAutoGenerate = !children && name
  return (
    <div
      ref={ref}
      className={cn(
        'relative flex h-10 w-10 shrink-0 overflow-hidden rounded-full',
        className,
      )}
      {...props}
    >
      {shouldAutoGenerate ? (
        <AvatarAutoGenerated name={name} />
      ) : (
        children
      )}
    </div>
  )
})
Avatar.displayName = 'Avatar'

const AvatarFallback = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn(
      'flex h-full w-full items-center justify-center rounded-full bg-muted text-xs font-medium',
      className,
    )}
    {...props}
  />
))
AvatarFallback.displayName = 'AvatarFallback'

// Auto-generated avatar component
function AvatarAutoGenerated({ name }: { name: string }) {
  const avatarIndex = hashName(name)
  const avatarUrl = AVATAR_SVGS[avatarIndex]

  return (
    <img
      src={avatarUrl}
      alt={name}
      className="h-full w-full object-cover"
    />
  )
}

const AvatarImage = React.forwardRef<
  HTMLImageElement,
  React.ImgHTMLAttributes<HTMLImageElement>
>(({ className, ...props }, ref) => (
  <img
    ref={ref}
    className={cn('aspect-square h-full w-full object-cover', className)}
    {...props}
  />
))
AvatarImage.displayName = 'AvatarImage'

export { Avatar, AvatarFallback, AvatarImage }