name: frontend
on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"
  pull_request:
    branches:
      - "main"
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
